backend:
  name: git-gateway
  branch: master
  local_backend: true
media_folder: "src/static/images"
public_folder: "/static/images"
site_url: "https://hopevauxhall.co.uk"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - {
    "label": "Pages",
    "name": "pages",
    "folder": "src/pages",
    "identifier_field": "title",
    "create": true,
    "slug": "{{ title }}",
    "editor": { "preview": false },
    "fields": [
      {
        "label": "Page Title",
        "name": "title",
        "widget": "string"
      },
      {
        "label": "Page Body",
        "name": "body",
        "widget": "markdown"
      }
    ]
  }
  - label: "People"
    name: "people"
    folder: "src/people"
    identifier_field: name
    create: true
    slug: "{{name}}"
    editor:
      preview: false
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Photo", name: "photo", widget: "image", required: false }
      - { label: "Short Bio", name: "shortBio", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown", required: false }

  - label: "Events"
    name: "events"
    folder: "src/events"
    identifier_field: title
    create: true
    slug: "{{title}}"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Location", name: "location", widget: "text", default: "Hope Church,\n105 Tyers Street,\nVauxhall,\nSE11 5HS"}
      - { label: "Date and Time", name: "date", widget: "datetime" }
      - { label: "Short Description", name: "shortDesc", widget: "string" }
      - { label: "External link", name: "link", widget: "string", required: false, hint: 'Make sure you start with an https://…'}
      - { label: "Body", name: "body", widget: "markdown", required: false }

  - label: "Sections"
    name: "sections"
    folder: "src/sections"
    identifier_field: navtitle
    create: true
    slug: "{{navtitle}}"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Nav Title", name: "navtitle", widget: "string" }
      - {
          label: "Lead Image",
          name: "leadimage",
          widget: "image",
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown" }
      - label: Next steps
        name: nextStep
        label_singular: Next step
        widget: list
        fields:
          - { name: title, label: Title, widget: string }
          - { name: link, label: Link, widget: string }

  - label: "Activities"
    name: "activities"
    folder: "src/activities"
    identifier_field: title
    create: true
    slug: "{{title}}"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Time", name: "time", widget: "string" }
      - {
          label: "Short Description",
          name: "shortDesc",
          widget: "string",
          required: false,
        }
      - {
          label: "Day",
          name: "day",
          widget: "select",
          options:
            [
              "Sunday",
              "Monday",
              "Tuesday",
              "Wednesday",
              "Thursday",
              "Friday",
              "Saturday",
            ],
        }
      - { label: "Body", name: "body", widget: "markdown", required: false }
  - name: "settings"
    label: "Settings"
    extension: json
    editor:
      preview: false
    files:
      - file: "src/_data/partners.json"
        label: "Partners"
        name: "partners"
        label_singular: "partner"
        collapsed: false
        allow_add: true
        fields:
          - label: Partners
            name: partners
            label_singular: partner
            widget: list
            fields:
              - { name: title, label: Name, widget: string }
              - { name: url, label: URL, widget: string }
              - { name: img, label: Logo, widget: image }

      - {
        "file": "src/_data/metadata.json",
        "label": "Homepage Menu",
        "name": "homepage_menu",
        "collapsed": false,
        "allow_add": false,
        "fields": [
          {
            "label": "Homepage Menu",
            "name": "homepage_menu",
            "widget": "list",
            "allow_add": false,
            "collapsed": false,
            "fields": [
              { "name": "link_text", "label": "Link Text", "widget": "string" },
              { "name": "link_url", "label": "Link URL", "widget": "string" }
            ]
          }
        ]
      }
