backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: master
  ### enable below lines for github integration ###
  # name: github
  # repo: surjithctly/neat-starter
media_folder: "src/static/images"
public_folder: "/static/images"
site_url: "https://hopevauxhall.co.uk"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: "People"
    name: "people"
    folder: "src/people"
    identifier_field: name
    create: true
    slug: "{{name}}"
    editor:
      preview: false
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Photo", name: "photo", widget: "image", required: false }
      - { label: "Short Bio", name: "shortBio", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown", required: false }
  - name: "settings"
    label: "Settings"
    extension: json

    editor:
      preview: false
    files:
      - file: "src/_data/partners.json"
        label: "Partners"
        name: "partners"
        label_singular: "partner"
        collapsed: false
        allow_add: true
        fields:
          - label: Partners
            name: partners
            label_singular: partner
            widget: list
            fields:
              - { name: title, label: Name, widget: string }
              - { name: url, label: URL, widget: string }
              - { name: img, label: Logo, widget: image }
